# yaml-language-server: $schema=https://raw.githubusercontent.com/asciidoctor/asciidoctor-intellij-plugin/main/src/main/resources/jsonSchemas/antoraPlaybookSchema.json

site:
  title: Reqstool Python Poetry Plugin Documentation
  url: https://github.com/reqstool/reqstool-python-poetry-plugin
  start_page: reqstool-python-poetry-plugin::index.adoc

content:
  sources:
    - url: ~+
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  attributes:
    kroki-server-url: https://kroki.io
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
